stages:
  - validate
  - build
  - deploy

.build-default:
  image: "fedora:34"
  before_script:
    - export PATH="$HOME/.local/bin:$PATH"
    - dnf install -y ${FEDORA_DEPS}
    - pip install --user "meson==0.56.0"

docs-validation:
  extends: .build-default
  stage: validate
  variables:
    # If docbook-style-xsl is installed, the xsltproc command reads
    # stylesheets from local files instead of http://docbook.sourceforge.net.
    # Faster and safer. Reading from docbook.sourceforge.net sometimes fails.
    FEDORA_DEPS:
      gcc
      gcc-c++
      gettext
      itstool
      libxml2
      docbook5-schemas
      docbook-style-xsl
      libxslt
      ninja-build
      python3
      python3-pip
      python3-wheel
    MESON_OPTIONS: "-Dbuild-examples=false -Dvalidation=true -Dbuild-translations=true -Dbuild-pdf=false"
  script:
    - meson setup ${MESON_OPTIONS} _build .
    - ninja -C _build
    # Translations are built on installation as long as issue
    # https://github.com/mesonbuild/meson/issues/2775 has not been fixed.
    - ninja -C _build install

html-tutorial:
  extends: .build-default
  stage: build
  variables:
    FEDORA_DEPS:
      gcc
      gcc-c++
      docbook-style-xsl
      libxslt
      ninja-build
      python3
      python3-pip
      python3-wheel
    MESON_OPTIONS: "-Dbuild-examples=false -Dvalidation=false -Dbuild-translations=false -Dbuild-pdf=false"
  script:
    - meson setup --prefix=/usr --datadir=share ${MESON_OPTIONS} _build .
    - ninja -C _build
    # Installation copies all documentation files to one directory.
    - ninja -C _build install
    - mkdir -p _build/docs/installed-tutorial
    - mv /usr/share/doc/gtkmm-4.0/tutorial/html _build/docs/installed-tutorial
  artifacts:
    when: always
    paths:
      - _build/docs/installed-tutorial

# Publish the gtkmm tutorial at gnome.pages.gitlab.gnome.org/gtkmm-documentation
pages:
  stage: deploy
  needs: ["html-tutorial"]
  script:
    - mkdir public
    - mv _build/docs/installed-tutorial/html/* public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
